# Generated by Django 4.0.2 on 2022-02-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enquiry_type', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
                ('enquiry_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Enquiry.enquirytype')),
            ],
        ),
    ]
